### PR TITLE
Create Contributors.md

### PR DESCRIPTION
**Pull request by mukulamy**
Created this file to track the contributors

### CODE REVIEW

**Comment by immattdavison** [comment]
We already track contributors in the built in GitHub option and in our README.md

**Comment by mukulamy** [comment]
> We already track contributors in the built in GitHub option and in our README.md

**Comment by mukulamy** [comment]
> We already track contributors in the built in GitHub option and in our README.md

I got it, but you could've just told me this rather than marking my PR as SPAM, I just got a Disqualification warning, Do you really think I was spamming?
Such a horrible experience

**Comment by immattdavison** [comment]
> > We already track contributors in the built in GitHub option and in our README.md
> 
> 
> 
> I got it, but you could've just told me this rather than marking my PR as SPAM, I just got a Disqualification warning, Do you really think I was spamming?
> 
> Such a horrible experience

A good way to avoid this in future is to open issues before PRs, also contribute to Thai main project rather than adding an incomplete file. 

Good luck with the rest of Hacktoberfest!

**Pull request closed without merging**
