### PR TITLE
Added Whitelisting Feature

### LINKED ISSUE #54: Create option to whitelist registrars
An option should be added to whitelist certain domains as some domains do link to cloud services that are more than domain registrars. 

This should be a simple input on the page, potentially have a second page that the user can switch to on the popup to view their whitelisted registrars.

### PR DESCRIPTION
**Pull request by Rutuj-Runwal**
Resolves #54 

Added an options page to whitelist domains 

Check out the Demo:

https://user-images.githubusercontent.com/59436520/194695882-53787e59-445f-4a49-88c0-a012deec9443.mp4

### CODE REVIEW

**Comment by immattdavison** [comment]
This is real nice @Rutuj-Runwal, is there a way we could include this in the extension popup itself? Like a separate tab it switches to in the popup? Just thinking out loud of ways we could improve it

**Comment by immattdavison** [comment]
> This is real nice @Rutuj-Runwal, is there a way we could include this in the extension popup itself? Like a separate tab it switches to in the popup? Just thinking out loud of ways we could improve it

If not tbh, I still really like this and would be happy to merge! 

Maybe a custom blacklist next? 👀

**Comment by Rutuj-Runwal** [comment]
> This is real nice @Rutuj-Runwal, is there a way we could include this in the extension popup itself? Like a separate tab it switches to in the popup? Just thinking out loud of ways we could improve it

It actually switches to an entirely new tab
If you check out the video that I linked when I click on the popup there is a new "settings" button in the corner and when I click on it, it takes us to the options page

**Comment by immattdavison** [comment]
> > This is real nice @Rutuj-Runwal, is there a way we could include this in the extension popup itself? Like a separate tab it switches to in the popup? Just thinking out loud of ways we could improve it
> 
> It actually switches to an entirely new tab
> If you check out the video that I linked when I click on the popup there is a new "settings" button in the corner and when I click on it, it takes us to the options page

Yeah I noticed that, was wondering if we could include it in the popup itself but actually I like the idea of having a full setting panel on that page. 

Nice work, will merge once I've had a chance to properly test.

**Comment by Rutuj-Runwal** [comment]
> > > This is real nice @Rutuj-Runwal, is there a way we could include this in the extension popup itself? Like a separate tab it switches to in the popup? Just thinking out loud of ways we could improve it
> > 
> > It actually switches to an entirely new tab
> > If you check out the video that I linked when I click on the popup there is a new "settings" button in the corner and when I click on it, it takes us to the options page
> 
> Yeah I noticed that, was wondering if we could include it in the popup itself but actually I like the idea of having a full setting panel on that page. 
> 
> Nice work, will merge once I've had a chance to properly test.

The popup will be unnecessarily clutter with all that extra code if it was included in the popup. I think it's better to keep it separate for now.

And regarding a custom Blocklist, it can be added easily.The hardest part was to set up something to whitelist first and create the whole flow of how things will work.We can slowly optimize it and add an Blocklist to this too.

Also if you find minor bugs do consider merging it still they can be fixed overtime🙂

**Comment by immattdavison** [comment]
> > > > This is real nice @Rutuj-Runwal, is there a way we could include this in the extension popup itself? Like a separate tab it switches to in the popup? Just thinking out loud of ways we could improve it
> > > 
> > > It actually switches to an entirely new tab
> > > If you check out the video that I linked when I click on the popup there is a new "settings" button in the corner and when I click on it, it takes us to the options page
> > 
> > Yeah I noticed that, was wondering if we could include it in the popup itself but actually I like the idea of having a full setting panel on that page. 
> > 
> > Nice work, will merge once I've had a chance to properly test.
> 
> The popup will be unnecessarily cluttered with all that extra code if it was included in the popup. I think it's better to keep it separate for now.
> 
> And regarding a custom Blocklist, it can be added easily.The hardest part was to set up something to whitelist first and create the whole flow of how things will work.We can slowly optimize it and add an Blocklist to this too.
> 
> Also if you find minor bugs do consider merging it still they can be fixed overtime🙂

Surely will merge shortly, just on mobile at the minute so difficult to look properly to see if there's any issues.

**Comment by Rutuj-Runwal** [comment]
@immattdavison Any bugs encountered in your testing?

**Comment by immattdavison** [comment]
> @immattdavison Any bugs encountered in your testing?

We need an option to remove each whitelisted domain individually rather than destroying the entire whitelist

**Comment by Rutuj-Runwal** [comment]
> > @immattdavison Any bugs encountered in your testing?
> 
> We need an option to remove each whitelisted domain individually rather than destroying the entire whitelist

Yaa but that's not a bug.
Will see what can be done about that. Anything else....

**Comment by immattdavison** [comment]
> > > @immattdavison Any bugs encountered in your testing?
> > 
> > 
> > We need an option to remove each whitelisted domain individually rather than destroying the entire whitelist
> 
> Yaa but that's not a bug. Will see what can be done about that. Anything else....

Not exactly bugs, more just personal preferences, I'm opening a few issues on the matter to help everything be tracked and fixed accordingly

**Comment by immattdavison** [comment]
Now that it is in production @Rutuj-Runwal it doesn't seem to be opening the setting page on click

**Comment by Rutuj-Runwal** [comment]
> Now that it is in production @Rutuj-Runwal it doesn't seem to be opening the setting page on click

Let me check. will fix it right away.

**Comment by immattdavison** [comment]
image
@Rutuj-Runwal

**Comment by Rutuj-Runwal** [comment]
> image
> @Rutuj-Runwal 

Yes working on a fix

**Comment by immattdavison** [comment]
> > image
> > @Rutuj-Runwal
> 
> Yes working on a fix

Nice!

**Comment by Rutuj-Runwal** [comment]
> > > image
> > > @Rutuj-Runwal
> > 
> > Yes working on a fix
> 
> Nice!

I am unable to reproduce the error on my side
Can you reload the extension or remove it and then load again?

**Comment by immattdavison** [comment]
> > > > image
> > > > @Rutuj-Runwal
> > > 
> > > 
> > > Yes working on a fix
> > 
> > 
> > Nice!
> 
> I am unable to reproduce the error on my side Can you reload the extension or remove it and then load again?

It appears to be working, not sure what happened there.

**Comment by Rutuj-Runwal** [comment]
Great!
It's a lot of new code so minor bugs are to be expected. Will continue to improve it.
Currently working on #17

**Comment by immattdavison** [comment]
> Great! It's a lot of new code so minor bugs are to be expected. Will continue to improve it. Currently working on #75

For sure! I appreciate all your contributions!

**Pull request merged**
