### PR TITLE
Revert "Redo domains.json implementation"

### PR DESCRIPTION
**Pull request by immattdavison**
Reverts immattdavison/NoMoreDomains#17

@Weredime this function completely breaks the system and does not redirect anywhere, instead it allows the user to continue to any blocked site

### CODE REVIEW

**Comment by Weredime** [comment]
@immattdavison This code should work on the latest build of Chrome stable. Can you please at least check the errors, and before merging the PR test it instead?

**Comment by immattdavison** [comment]
> @immattdavison This code should work on the latest build of Chrome stable. Can you please at least check the errors, and before merging the PR test it instead?

I'm using the latest stable build of chrome with no luck, any ideas?

**Comment by Weredime** [comment]
@immattdavison Could you check the errors that were produced when running #17? It shouldn't error in any way, since I am using Chrome.

**Comment by immattdavison** [comment]
> @immattdavison Could you check the errors that were produced when running #17? It shouldn't error in any way, since I am using Chrome stable latest.

image

image

Please be sure you are writing in terms of Chrome Extensions MV3

**Comment by Weredime** [comment]
> Please be sure you are writing in terms of Chrome Extensions MV3

[I am](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/).

Does the manifest have the "declarativeNetRequestWithHostAccess" permission? It should, otherwise it won't work. This Pull Request should have it, nonetheless

**Comment by immattdavison** [comment]
> > Please be sure you are writing in terms of Chrome Extensions MV3
> 
> [I am](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/).
> 
> Does the manifest have the "declarativeNetRequestWithHostAccess" permission? It should, otherwise it won't work. This Pull Request should have it, nonetheless

that seems likely to be the issue, I don't see that file in your PR

**Comment by immattdavison** [comment]
@Weredime if you can pull with that change I should be able to fix it!

**Pull request merged**
